Ctrl+LEFT playlist-prev
Ctrl+RIGHT playlist-next

, frame-back-step
. frame-step

c cycle sub-visibility
h script-binding select/select-watch-history

SPACE cycle pause
LEFT seek -5
RIGHT seek 5

k cycle pause
j seek -10
l seek 10

m cycle mute
DOWN add volume -5
UP add volume 5
