hr-seek=yes
keep-open=yes
save-position-on-quit=yes
write-filename-in-watch-later-config=yes
no-input-default-bindings
save-watch-history

script-opts=ytdl_hook-ytdl_path=yt-dlp
cache=yes
demuxer-max-bytes=500MiB
demuxer-max-back-bytes=200MiB
ytdl-format="bestvideo[height<=1080]+bestaudio/best"
